### test
GET http://localhost:5000/test

###CREATE ADMIN
POST http://localhost:5000/users
Content-Type: application/json

{
    "name":"admin",
    "email":"admin@gmail.com",
    "password":"123456",
    "confPassword":"123456",
    "role":"admin"

}

###LOGIN ADMIN
POST http://localhost:5000/login
Content-Type: application/json

{
    "email":"admin@gmail.com",
    "password":"123456"
  
}

###GET users
GET http://localhost:5000/users

###
POST http://localhost:5000/correctTranscribe
Content-Type: application/json

{
"uuid":"b29178df-06d1-44fe-89e7-033a8a77e700",
"textId":"1",
"desc":"Initial transcription here",
"speakers":"2"
}

###
POST http://localhost:5000/summarize
Content-Type: application/json

{
    "textId":"2"
}

###
GET http://localhost:5000/history/user/b29178df-06d1-44fe-89e7-033a8a77e700

